//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ValiModern.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int id { get; set; }
        public int order_id { get; set; }
        public int sender_id { get; set; }
        public int receiver_id { get; set; }
        public string message1 { get; set; }
        public Nullable<bool> is_read { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
